[package]
name = "rustduino"
version = "0.1.0"
authors = ["Mshivam2409 <me@shivammalhotra.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
